#!/usr/bin/env bash

set -euEo pipefail

# Install brew
wget -qO - https://git.io/JTlbH?=brew-ubuntu | bash

brew install terraform-docs
brew install pre-commit
brew install tflint
brew install shfmt
brew install shellcheck
