#!/usr/bin/env bash

set -euEo pipefail

# Add Repo & Install Terraform
wget -qO - https://apt.releases.hashicorp.com/gpg |
  sudo apt-key add -

sudo apt-add-repository \
  "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

sudo apt-get update -y
sudo apt-get install -y terraform
