#!/usr/bin/env bash
#
# Environment:
#   $PUBLIC_IP
#   $OPENVPN_PORT
#   $OPENVPN_CLIENT_NAME
#

set -euEo pipefail

cd ~/data/docker/openvpn

cat <<EOF >.env
# OPENVPN
OPENVPN_PORT=${OPENVPN_PORT}
OPENVPN_PROTOCOL=${OPENVPN_PROTOCOL}
EOF

# Initialize the configuration files and certificates
docker-compose run --rm openvpn \
  ovpn_genconfig -u "${OPENVPN_PROTOCOL}://${PUBLIC_IP}"

echo "$PUBLIC_IP" |
  docker-compose run --rm openvpn \
    ovpn_initpki nopass

# Generate a client certificate without a passphrase
docker-compose run --rm openvpn \
  easyrsa build-client-full "${OPENVPN_CLIENT_NAME}" nopass

# Retrieve the client configuration with embedded certificates
docker-compose run --rm openvpn \
  ovpn_getclient "${OPENVPN_CLIENT_NAME}" >~/"${OPENVPN_CLIENT_NAME}.ovpn"

# Add 'duplicate-cn' option to vpn config
docker-compose run --rm --entrypoint /bin/sh \
  openvpn \
  -c 'echo duplicate-cn >> /etc/openvpn/openvpn.conf'
# docker exec "$vpn_container" sh -c 'echo \"duplicate-cn\" >> /etc/openvpn/openvpn.conf'

# Replaces vpn host port
sed -i "s/1194 ${OPENVPN_PROTOCOL}/${OPENVPN_PORT} ${OPENVPN_PROTOCOL}/" \
  ~/"${OPENVPN_CLIENT_NAME}.ovpn"

# Start openvpn service
docker-compose up -d
