#!/usr/bin/env bash
#
# Environment:
#   $DOCKER_AUTH
#

set -euEo pipefail

# Install dependencies
sudo apt-get install -y make git

# Create docker auth config
mkdir ~/.docker
cat <<-EOF >~/.docker/config.json
{
  "auths": {
    "https://index.docker.io/v1/": {
      "auth": "${DOCKER_AUTH}"
    }
  },
  "HttpHeaders": {
    "User-Agent": "Docker-Client/$(docker --version | grep -Po '\d+\.\d+\.\d+') (linux)"
  }
}
EOF

# Install cron script
chmod +x ~/data/umdi/update-my-docker-images
sudo mv ~/data/umdi/update-my-docker-images /etc/cron.monthly
