#!/usr/bin/env bash

# Environment:
#   $SS_PORT
#   $SS_PASSWORD
#
set -euEo pipefail

cd ~/data/docker/ss-server

cat <<EOF >.env
# SSSERVER
SS_PORT=${SS_PORT}
SS_PASSWORD='${SS_PASSWORD}'
EOF

# Start openvpn service
docker-compose up -d
